Added pundit authorization
dgarcia13-99/industrial-auth-1 pull request #2
Opened 2024-11-01 20:37 UTC by dgarcia13-99

Added pundit authorization to comments, photos, follow_requests, and users.

2024-11-01 20:53 UTC, hatcheta1 commented on app/controllers/application_controller.rb
nice job securing by default!

2024-11-01 20:53 UTC, hatcheta1 commented on app/controllers/comments_controller.rb
> +  before_action {authorize(@comment || Comment)}
great use of ```before_action```!

2024-11-01 20:53 UTC, hatcheta1 commented on app/controllers/users_controller.rb
<img width="1432" alt="Screenshot 2024-11-01 at 3 52 23 PM" src="https://github.com/user-attachments/assets/58e1f70f-21ab-490b-b315-e3255eb1ff6e">
got this error when I loaded the live app preview

2024-11-04 18:05 UTC, armstrca commented
Alice seems to be able to edit and delete anyone else's photos and comments still. The actions shouldn't work and the icons shouldn't show up.

![Screenshot 2024-11-04 120147](https://github.com/user-attachments/assets/d817a139-3279-4e5e-ac3b-8aa95783f5a0)
![Screenshot 2024-11-04 120122](https://github.com/user-attachments/assets/72c4b3bf-8680-4788-b3c1-a3c6b3dc60aa)

2024-11-04 18:19 UTC, armstrca requested changes
Make sure to test things out in the live preview before committing/making PRs.

Current_user should be able to see a private user's profile page, but *not* the private user's photos.

2024-11-04 18:19 UTC, armstrca commented on app/controllers/users_controller.rb
Same.

2024-11-04 20:51 UTC, dgarcia13-99 commented on app/controllers/users_controller.rb
Thank you for the feedback! I had a syntax error, but it should be working now!

2024-11-05 18:03 UTC, armstrca requested changes

2024-11-05 18:03 UTC, armstrca commented on app/controllers/photos_controller.rb
![Screenshot 2024-11-05 115913](https://github.com/user-attachments/assets/212ef221-6563-4646-bd26-44c958a6f78c)

2024-11-05 18:03 UTC, armstrca commented on app/controllers/comments_controller.rb
![Screenshot 2024-11-05 120011](https://github.com/user-attachments/assets/24278433-5bd9-4e90-9ac9-801b663192fe)

2024-11-05 18:03 UTC, armstrca commented on app/views/photos/show.html.erb
Put some handling in here for cases in which `photo.owner` is private and `current_user` is not a follower of `photo.owner`

2024-11-05 22:16 UTC, armstrca approved these changes
boom

2024-11-05 22:19 UTC, merged